version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Sao_Paulo
  pull-request-branch-name:
    separator: "-"
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.11.0
    - 1.12.0
    - 1.12.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: json
    versions:
    - 2.5.1
  - dependency-name: rake
    versions:
    - 13.0.3
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: websocket-extensions
    versions:
    - 0.1.5
  rebase-strategy: disabled
