require:
  - rubocop-performance

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30

AllCops:
  TargetRubyVersion: 2.7.8
  DisplayCopNames: true
