patterns:
  - acidente
  - acompanhante
  - bandido
  - bosta
  - bravecto
  - buceta
  - boceta
  - bunda
  - cagada
  - cagar
  - caralho
  - caro
  - center
  - cobasi
  - corrupcao
  - crime
  - cupom
  - cupon
  - corno
  - econom
  - escandalo
  - espancar
  - estragado
  - estragar
  - furtar
  - furto
  - fezes
  - http
  - idiota
  - igreja
  - inferno
  - ladrao
  - lixo
  - lovebits
  - maldade
  - maldito
  - marginal
  - meliuz
  - merda
  - morte
  - palhacada
  - palhaco
  - porra
  - pedofilia
  - pelando
  - pessimo
  - petcenter
  - pet-center
  - p[e3]?t([^a-zA-Z]*)l
  - pt([^a-zA-Z]*)lv
  - petz
  - picodi
  - piromba
  - politica
  - porcaria
  - porno
  - pornografia
  - prejuizo
  - premier
  - puta
  - penis
  - rasgado
  - rasgar
  - recall
  - reclamacao
  - reclamar
  - reclame
  - roubalheira
  - roubar
  - roubo
  - royal
  - ruim
  - sensual
  - sex
  - sexo
  - sexshop
  - sexy
  - slugify
  - taxa
  - xana
  - xoxota
  - tragedia
  - tributacao
  - tributo
  - usado
  - whiskas
  - viado
  - veado
  - pet[-_]?love
  - \d{2}[%-_]?off
  - \d{2}[%-_]?extra
  - off[-_]?\d{2}%?
  - extra[-_]?\d{2}%?
  - the
  - prime
  - asjoiasdolu
  - petcamp
  - mondopet
  - mundopet
  - petland
  - lovepetsz
  - petklove
  - produto
  - produtos
  - promocao
  - loja
  - portopet
